# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 13ee94835f0fd813d56dc446beaef4d466b11ccfc1e550824173a15c278de73f74fa18cd07a95c591ec1b4595541603768a0c7f8960cdb92d72a78508f74a42e

test:
  secret_key_base: efb9ad478f5ee990e266523528ea70b5a43a2c4dc5a547e89c237125d0b7710473f6db922c9a66f17b794e9db16f6b8fb48bba84ceeadc33657a199678265abd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
